---
- name: "Copy nginx file"
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    force: yes

- name: "Install nginx package"
  yum:
    name: "nginx"
    state: latest
    update_cache: yes

- name: Enabling nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started