---
- name: Importing tenant information and credentials
  include_vars:
    file: "credentials.yml"

- name : Create new instance {{ name }}
  os_server:
    state: present
    auth:
      auth_url: "{{ auth_url  }}"
      username: "{{ username  }}"
      password: "{{ password  }}"
      tenant_name: "{{ tenant_name  }}"
      user_domain_name: "{{ user_domain_name  }}"
      project_id: "{{ project_id }}"
    name: "{{ name  }}"
    image: "{{ image }}"
    flavor: "{{ flavor  }}"
    key_name: "{{ keypair_id }}"
    nics:
      - net-id: "{{ net_id }}"
    meta:
      type: "{{ type }}"
      project: "{{ project }}"