---
- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Importing hosts information"
      include_vars:
        file: "hosts.yml"
    - name: "Deploying hosts"
      include_role: 
        name: openstack
      vars:
        action: "DEPLOY"
      loop: "{{ hosts }}"
      loop_control:
        loop_var: metadata