---
- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Creating raw inventory"
      include_role: 
        name: inventory
    - name: "Importing hosts information"
      include_vars:
        file: "hosts.yml"
    - name: "Deploying hosts"
      include_role: 
        name: openstack
      vars:
        action: "DEPLOY"
      loop: "{{ hosts }}"
      loop_control:
        loop_var: metadata
    - name: Get inventory
      meta: refresh_inventory

- name: Deploy roles common, nginx
  hosts: dromero
  gather_facts: true
  become: yes
  roles:
    - common
    - nginx