hosts:
  - name: dromero
    number: 1
    image: RHEL7.5
    flavor: d1.medium
    net_id: 40128f87-4009-4599-a0b6-cdf237842c43
    net_name: cop_network
    type: dromero
    keypair_id: testKeyPair
    project: cock
