---
- name: Create inventory folder
  file:
    path: inventories/
    state: directory

- name: Delete old inventory
  file:
    path: inventories/hosts
    state: absent

- name: Create inventory file
  file:
    path: inventories/hosts
    state: touch

- name: Create inventory role files folder
  file:
    path: "{{ playbook_dir }}/roles/inventory/files/"
    state: directory

- name: Check if internal user pass exists
  local_action:
    module: stat
    path: "{{ playbook_dir }}/roles/inventory/files/internal_pass"
  register: pass_result

- name: Create monitoring_user pass
  local_action:
    module: copy
    content: "{{ lookup('password', '/dev/null length=35 chars=ascii_letters') }}"
    dest: "{{ playbook_dir }}/roles/inventory/files/internal_pass"
  when: pass_result.stat.exists == False

- name: Set monitoring_user pass
  set_fact:
    internal_pass: "{{ lookup('file', '{{ playbook_dir }}/roles/inventory/files/internal_pass') }}"

- name: Add all vars
  lineinfile:
    path: "{{ playbook_dir }}/inventories/hosts"
    line: "{{ item }}"
    create: yes
  loop:
    - '[all:vars]'
    - 'ansible_ssh_private_key_file={{ playbook_dir }}/testkeypair.pem'
    - 'internal_pass={{ internal_pass }}'
    - 'default_db=cock'
    - 'internal_user=cocky'
  no_log: true