---
- import_tasks: prerequisites.yml
  become: true
  tags:
    - gitea

- import_tasks: install.yml
  become: true
  tags:
    - gitea

- import_tasks: configure.yml
  become: true
  tags:
    - gitea