---
- name : Create new instance {{ name }}
  os_server:
    state: present
    auth:
      auth_url: "{{ auth_url  }}"
      username: "{{ username  }}"
      password: "{{ password  }}"
      tenant_name: "{{ tenant_name  }}"
      user_domain_name: "{{ user_domain_name  }}"
      project_id: "{{ project_id }}"
    name: "{{ name }}"
    image: "{{ metadata.image }}"
    flavor: "{{ metadata.flavor  }}"
    key_name: "{{ metadata.keypair_id }}"
    nics:
      - net-id: "{{ metadata.net_id }}"
    meta:
      type: "{{ metadata.type }}"
      project: "{{ metadata.project }}"
  register: result

- name: Add instance {{ name }} to inventory
  lineinfile:
      path: "{{ playbook_dir }}/inventories/hosts"
      line: "{{ name }} ansible_ssh_user=cloud-user ansible_host={{ result.openstack.accessIPv4 }}"
      create: yes
    