---
- name: Importing tenant information and credentials
  include_vars:
    file: "credentials.yml"
  no_log: true

- name: Add metagroup for inventory
  lineinfile:
    path: "{{ playbook_dir }}/inventories/hosts"
    line: "[{{ metadata.name }}]"
    create: yes

- include_tasks: create.yml
  vars:
    name: "{{ metadata.name }}-{{ item }}"
  with_sequence: start=1 end={{ metadata.number | int }}
  when: action == 'DEPLOY'