---
- name: Importing tenant information and credentials
  include_vars:
    file: "credentials.yml"
  no_log: true
  tags:
    - create_inventory

- include_tasks: create.yml
  vars:
    name: "{{ metadata.name }}-{{ item }}"
    host_state: "present"
  with_sequence: start=1 end={{ metadata.number | int }}
  when: action == 'DEPLOY'
  tags:
    - create_inventory

- include_tasks: destroy.yml
  vars:
    name: "{{ metadata.name }}-{{ item }}"
    host_state: "absent"
  with_sequence: start=1 end={{ metadata.number | int }}
  when: action == 'DESTROY'