---
- name: Remove pyOpenSSL from yum
  yum:
    name: pyOpenSSL
    state: absent

- name: Download pip
  shell: "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py --insecure"
  args:
    chdir: "/tmp/"

- name: "Install pip"
  shell: "python /tmp/get-pip.py"

- name: "Install pip packages"
  pip:
    name: "{{ item }}"
  loop:
    - setuptools==40.8.0
    - cryptography==2.5.0
    - pyOpenSSL==19.1.0